import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"]
})

export const metadata = {
  title: "Unstop Igniters Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased w-full container mx-auto max-w-7xl`}
      >
        {children}
      </body>
    </html>
  );
}
